# Generated by Django 5.0.3 on 2024-08-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_remove_savollar_fakultet_remove_jadval_fakultet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapallar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
